# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/github-script@v2
      id: history
      with:
        result-encoding: string
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
         const matched = context.payload.head_commit.message.match(/(?<=DEPLOY \|).*?(?=\s*\|)/gs);
                      const list = matched && Array.isArray(matched) && matched.length > 0 ? matched[0].trim() : null;
                      if (list === "ALL") {
                             return "--all";
                         } else if (list) {
                             return list;
                         }  
                                   
    - name: List services
      id: services
      run: |
       if [[ ${{steps.history.outputs.result}} == *"--"* ]]; 
       then 
          echo ::set-output name=list::$(node ./node_modules/@nrwl/cli/bin/nx.js affected:apps --plain ${{steps.history.outputs.result}} ) 
       else 
          echo ::set-output name=list::${{steps.history.outputs.result}}
       fi
       
    - name: Echo services
      run: echo ${{ steps.services.outputs.list }}
